### PR TITLE
Skip rendering text when font size would be zero

### PR DESCRIPTION
**Pull request by akx**
Refs #217

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Thanks

**Comment by WhyNotHugo** [comment]
Oh, care to add a CHANGELOG entry for this?

**Comment by akx** [comment]
@WhyNotHugo Sure thing (though it's not really a change that should be user-facing).

**Comment by WhyNotHugo** [comment]
Previously this worked "by coincidence", but not it is fixed and I'd consider it something that can be relied upon.

**Comment by akx** [comment]
@WhyNotHugo Could we maybe get a release out that'd include this? Thanks :)

**Pull request merged**
