### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by jinlygenius**
remove parameter 'options' in function generate, barcode = get(name, code, writer, options), as passing 'options' raises exception in Code128(code, writer, **options)

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Do you have an example of failing code, or of what this change fixes?
This seems to work fine for me:

```python
import barcode
from barcode.writer import ImageWriter

barcode.generate('code128', 'hi', ImageWriter(), '/tmp/1.png')
```

**Comment by mokko** [comment]
Doesn't seem to work when setting these kind of options={'module_width':4.0, 'module_height':10.0}

**Comment by AlanSwenson** [comment]
I believe this is the same error in issue #38

**Comment by WhyNotHugo** [comment]
Finally figured it out. This PR breaks other types of barcodes. I've pushed a different change that also fixes this issue. Thanks for the PR though, that to it I found where the problem was! :cake:

**Pull request closed without merging**
