### PR TITLE
[#135] Optimized SVG output by removing redundant geometry

### PR DESCRIPTION
**Pull request by timsat**
This reduces output SVG almost twice by skipping drawing spaces over a background

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Smart.

I'll try this a bit to make sure it works fine and go ahead and merge, though the idea makes perfect sense and changes look solid.

**Comment by timsat** [comment]
> Smart.
> 
> I'll try this a bit to make sure it works fine and go ahead and merge, though the idea makes perfect sense and changes look solid.

awesome, thanks!

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by timsat** [comment]
@WhyNotHugo, is there any expectation on when the update could be published to PyPI?

**Pull request merged**
